spring.application.name=FlixPay
spring.datasource.url=jdbc:h2:mem:flixpay
spring.datasource.drive-class-name=org.h2.Driver
spring.datasource.username=vb
spring.datasource.password=1234
spring.jpa.database-plataform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console